/* Copyright © 2020, Imesh Chamara. All rights reserved. */
import comm from './common_page.js'

const dmca = comm({name: 'dmca', title: 'DMCA Notice of Copyright Infringement', content: [
	{t:'span', cl: 'title', txt: 'Legal Disclaimer'},
	{t:'span', cl: 'cont', txt: "The author is not responsible for any contents linked or referred to from his pages – If any damage occurs by the use of information presented there, only the author of the respective pages might be liable, not the one who has linked to these pages. IAnime doesn't host any content\n\nAll IAnime does is link or embed content that was uploaded to popular Online Video hosting sites like Veoh.com / Megavideo.com / Youtube.com / Google Video. All youtube/veoh/megavideo/googlevideo users signed a contract with the sites when they set up their accounts which forces them not to upload illegal content. By clicking on any Links to videos while surfing on IAnime you watch content hosted on third parties and IAnime cant take the responsibility for any content hosted on other sites.\n\nWe do not upload any videos nor do we know who and where videos are coming from. We do not promote any illegal conduct of any kind. Links to the videos are submitted by users and managed by users."},
	{t:'span', cl: 'title', txt: 'DMCA Notice of Copyright Infringement'},
	{t:'span', cl: 'cont', txt: "IAnime is an online service provider as defined in the Digital Millennium Copyright Act."},
	{t:'span', cl: 'cont', txt: "We provide legal copyright owners with the ability to self-publish on the Internet by uploading, storing and displaying various types of media. We do not actively monitor, screen or otherwise review the media which is uploaded to our servers by users of the service.\nWe take copyright violation very seriously and will vigorously protect the rights of legal copyright owners.\nIf you are the copyright owner of content which appears on the IAnime website and you did not authorize the use of the content you must notify us in writing in order for us to identify the allegedly infringing content and take action."},
	{t:'span', cl: 'cont', txt: "We will be unable to take any action if you do not provide us with the required information, so please fill out all fields accurately and completely. You may make a written notice via e-mail, facsimile or postal mail to our DMCA Agent as listed below. Your written notice must include the following:"},
	{t:'span', cl: 'item', txt: "Specific identification of the copyrighted work which you are alleging to have been infringed. If you are alleging infringement of multiple copyrighted works with a single notification you must submit a representative list which specifically identifies each of the works that you allege are being infringed."},
	{t:'span', cl: 'item', txt: "Specific identification of the location and description of the material that is claimed to be infringing or to be the subject of infringing activity with enough detailed information to permit us to locate the material. You should include the specific URL or URLs of the web pages where the allegedly infringing material is located."},
	{t:'span', cl: 'item', txt: "Information reasonably sufficient to allow us to contact the complaining party which may include a name, address, telephone number and electronic mail address and signature at which the complaining party may be contacted."},
	{t:'span', cl: 'item', txt: "A statement that the complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent or the law."},
	{t:'span', cl: 'item', txt: "A statement that the information in the notification is accurate, and under penalty of perjury that the complaining party is authorized to act on behalf of the owner of an exclusive right that is allegedly infringed."},
	{t:'span', cl: 'cont', txt: "Written notice should be sent to our designated agent as follows:"},
	{t:'span', cl: 'cont', txt: "DMCA AGENT Email: imesh1chamara [at] gmail.com"},
]})

export {dmca}
